version: '3.7'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root!
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"