version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"
  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - mariadb
      - redis
  mariadb:
    container_name: mariadb
    image: mariadb:10
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root!
    ports:
      - "3306:3306"
  application-demo:
    hostname: application
    restart: on-failure
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nginx
    deploy:
      replicas: 3