spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/database_name?useUnicode=true
    username: demo
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  executorType: BATCH